### ISSUE TITLE
[EPIC] Images in the new theme

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/theme-refacto#147]
HighDPI images for every size is a thing of a past. We must do it by source sets.

![1_rMgY0FiD7R-_eq1_TXkUpg](https://user-images.githubusercontent.com/6097524/149043198-d403cc77-dde1-4800-93f6-83c405582a7e.jpeg)

### Planning
- [x] Plan how to serve images to the FO, I would like a meet between some core peoples in order to speak about this images system.
- [ ] Specify which widths of images we want to use in the new theme.
  - We need to get precise width list of images to be used in the new theme, for each object.
  - We need to take account also the scaled devices. Sizes should overlay nicely for both 1x and 2x scaled devices, maybe even for 3x devices.
  - For example products: 200px, 400px, 600px, 800px, 1200px, 1600px - These sizes will nicely overlay for both 1x and 2x devices.

**TODO:**
| Name  | Size |
| ------------- | ------------- |
| product_160  | 160 x 160  |
| product_320  | 320 x 320  |
| product_640  | 640 x 640  |
| product_800  | 800 x 800  |
| product_1280  | 1280 x 1280  |
| product_1600  | 1600 x 1600  |
| category_160  | 160 x 160  |
| category_320  | 320 x 320  |
etc.

### Implementing the image creation
- [ ] To prevent BC breaks, we decided to keep the current image formats in order not to break modules.
- [ ] Add support for another image formats to be rendered alongside of current JPG/PNG combo- WebP, AVIF.
  - https://github.com/PrestaShop/PrestaShop/issues/10356 - not properly integrated yet, waiting for https://github.com/PrestaShop/PrestaShop/pull/24159 by @lmeyer1
  - https://github.com/PrestaShop/PrestaShop/issues/27264
- [ ] Change the image format settings in BO to checkboxes. We need to generate the formats simultaneously.
  - Which styles do you want to generate? User will check JPG/PNG, WEBP, AVIF. 
  - AVIF will be available only on PHP 8.1+, because the previous versions don't support generating it yet. On lower versions of PHP, it will be greyed out with an alert to upgrade.

### Making it available for use in FO
- [ ] There will be a new attribute in `product.image` object in front office called `sources`.
  - This array will contain subarrays called, depending on available formats -  `jpg`, `webp`, `avif`.
  - Each format will contain the data for every dimension.
  - Theme could easily check if the format exist by doing `{if $image.sources.webp}` for example.
  - It could also contain the link to the original image, in order for it to be used for lightboxes and other stuff.

### Putting it to use
- [ ] Build nice awesome picture tags in the theme, with all formats and a basic JPG fallback.
- [ ] Provide browser with the sizes tag, for all cases when the image is only taking a fraction of viewport width. Since the browser is not aware of the layout, it will assume the image will take up the whole viewport width and download a much bigger image than required. This prevents it and **allows the browser to download the image even before parsing the CSS.**

```
<picture>
<source srcset="/img/product_1920.avif 1920w, /img/product_1280.avif 1280w, 
  /img/product_640.avif640w, /img/product_320.avif 320w"
  sizes="(min-width: 1320px) 600px, (min-width: 768px) 50vw, 100vw" 
  type="image/avif"/>
<source srcset="/img/product_1920.webp 1920w, /img/product_1280.webp 1280w, 
  /img/product_640.webp 640w, /img/product_320.webp 320w"
  sizes="(min-width: 1320px) 600px, (min-width: 768px) 50vw, 100vw"
  type="image/webp"/>
<img srcset="/img/product_1920.jpg 1920w, /img/product_1280.jpg 1280w,
    /img/product_640.jpg 640w, /img/product_320.jpg 320w"
  sizes="(min-width: 1320px) 600px, (min-width: 768px) 50vw, 100vw"
  src="/img/1920.jpg"
  alt="Product"
  width="1920"
  height="1920">
</picture>
```

### Clean up and improvements
- [ ] Deprecate HighDPI images, the sizes have the same effect and does not generate duplicate images.
  - Imagine you have product size like home_default 400px and large_default 800px. The HightDPI image function generates home_default_2x in 800px width, while we already have that dimension. It's only a waste of space.
  - https://github.com/PrestaShop/PrestaShop/issues/26886
- [ ] Find a way to make core completely independent on the long-known image format names. Every theme can bring their own formats. If the devs were selfish, it will completely break the core and FO.
- [ ] Find a way to make a backward compatible bridge for every legacy module asking for a dimension that does not exist. We should provide the nearest bigger image size.

**Comment by lmeyer1** [comment]
Thanks @Hlavtox

**Comment by NeOMakinG** [comment]
Closing in favor of https://github.com/PrestaShop/PrestaShop/issues/27318
